# Formato: nome_processo  porcentagem  ação  [egr_strategy] [ingr_strategy]
# ação: allow | block
# egr_strategy (opcional, default = drop): drop | edt
# ingr_strategy (opcional, default = drop): drop | ecn
brave  40  allow  edt   ecn
*      60  allow
malware 0  block
