# Formato: nome_processo  porcentagem  ação  [egr_strategy] [ingr_strategy]
# ação: allow | block
# egr_strategy (opcional, default = drop): drop | edt
# ingr_strategy (opcional, default = drop): drop | ecn
firefox 100  allow  edt   ecn
*       0    block
malware 0    block
